version: '3.7'
services:

  caddy:
    container_name: caddy
    image: caddy:${CADDY_VERSION}
    volumes:
      - ${CADDY_CONF_DIR}:/config
      - ${CADDY_DATA_DIR}:/data
      - ${WP_DATA_DIR}:/var/www/html
    ports:
      -   80:80
      -   443:443
      -   2019:2019
    links:
      - nginx
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WP_DATA_DIR}:/var/www/html
    ports:
      - '8080:80'
    links:
      - wordpress
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    image: wordpress:${WP_VERSION}
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${WP_DATA_DIR}:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST:mariadb
      - WORDPRESS_DB_USER:${MDB_USER}
      - WORDPRESS_DB_PASSWORD:${MDB_PASSWORD}
      - WORDPRESS_DB_NAME:${MDB_NAME}
      - WORDPRESS_TABLE_PREFIX:${MDB_TABLE_PREFIX}
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: db
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - ${MDB_DATA_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    volumes:
      - ${DB_CACHE_DATA_DIR}:/data
    restart: unless-stopped
    links:
      - wordpress
