version: '3.7'
services:

  caddy:
    container_name: WebServer
    image: alpine:3.12
    build: /caddy/.
    volumes:
      - ${CADDY_CONFIG_DIR}:/config/caddy
      - ${CADDY_DATA_DIR}:/data/caddy
      - ${WP_DATA_DIR}:/var/www/html
      - ./caddy/.caddy:/root/.caddy

		:/etc/caddy \
		:/usr/share/caddy

    ports:
      -   80:80
      -   443:443
      -   2019:2019
  
  nginx:
    container_name: AppServer
    image: nginx:${NGINX_VERSION}
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WP_DATA_DIR}:/var/www/html
    ports:
      - '8080:80'
    links:
      - wordpress
    restart: unless-stopped

  mariadb:
    container_name: Database
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - ${MDB_DATA_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped

  redis:
    container_name: dbCache
    image: redis:${REDIS_VERSION}
    volumes:
      - ${DB_CACHE_DATA_DIR}:/data
    restart: unless-stopped
    links:
      - wordpress

  wordpress:
    container_name: WP_PHP_FPM_7.4
    image: wordpress:${WP_VERSION}
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${WP_DATA_DIR}:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST:mariadb
      - WORDPRESS_DB_USER:${MDB_USER}
      - WORDPRESS_DB_PASSWORD:${MDB_PASSWORD}
      - WORDPRESS_DB_NAME:${MDB_NAME}
      - WORDPRESS_TABLE_PREFIX:${MDB_TABLE_PREFIX}
    depends_on:
      - mariadb
    restart: unless-stopped

 
