version: '3.7'
services:

  rdbms:
    container_name: rdbms
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped

  redis:
    container_name: dbCache
    image: redis:${REDIS_VERSION}
    volumes:
      - ./redis:/data
    restart: unless-stopped
    links:
      - wordpress

  wordpress:
    container_name: wp_php_fpm
    image: wordpress:${WP_VERSION}
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST:rdbms
      - WORDPRESS_DB_USER:${MDB_USER}
      - WORDPRESS_DB_PASSWORD:${MDB_PASSWORD}
      - WORDPRESS_DB_NAME:${MDB_NAME}
      - WORDPRESS_TABLE_PREFIX:${MDB_TABLE_PREFIX}
    depends_on:
      - rdbms
    restart: unless-stopped

  nginx:
    container_name: appServer
    image: nginx:${NGINX_VERSION}
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WP_DATA_DIR}:/var/www/html
    ports:
      - '8080:80'
    links:
      - wordpress
    restart: unless-stopped
