version: '3.7'
services:

  caddy:
    container_name: caddy
    image: "techwise/reverse-proxy:${CADDY_VERSION_TAG}"
    build:
      dockerfile: ${CADDY_DOCKERFILE}
    volumes:
      - ${CADDY_DIR}:/root/.caddy
      - ${CADDY_SSL}:/root/certs # to sync SSL certificates to Caddy
      - ${CADDYFILE}:/etc/caddy/Caddyfile # to mount custom Caddyfile
    ports:
      -   80:80
      -   443:443
      -   2019:2019
    links:
      - nginx
    restart: unless-stopped
    networks:
      shopnet:
        ipv4_address: 172.28.1.1

  nginx:
    container_name: nginx
    image: "techwise/web_server:${NGINX_VERSION_TAG}"
    build:
      dockerfile: ${NGINX_DOCKERFILE}
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WP_DATA_DIR}:/var/www/html
    ports:
      - '8080:80'
    links:
      - wordpress
    restart: unless-stopped
    networks:
      shopnet:
        ipv4_address: 172.28.1.2

  wordpress:
    container_name: wordpress
    image: "techwise/wp_app:${WP_VERSION_TAG}"
    build:
      dockerfile: ${WORDPRESS_DOCKERFILE}
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${WP_DATA_DIR}:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST:db
      - WORDPRESS_DB_USER:${DB_USER}
      - WORDPRESS_DB_PASSWORD:${DB_PASSWORD}
      - WORDPRESS_DB_NAME:${DB_NAME}
      - WORDPRESS_TABLE_PREFIX:${DB_TABLE_PREFIX}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      shopnet:
        ipv4_address: 172.28.1.3

  db:
    container_name: db
    image: techwise/app_db:${DB_VERSION_TAG}
    volumes:
      - ${DB_DATA_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
    networks:
      shopnet:
        ipv4_address: 172.28.1.4

  redis:
    container_name: redis
    image: "techwise/db_cache:${REDIS_VERSION_TAG}"
    build:
      dockerfile: ${REDIS_DOCKERFILE}
    volumes:
      - ${DB_CACHE_DATA_DIR}:/data
    restart: unless-stopped
    links:
      - wordpress
    networks:
      shopnet:
        ipv4_address: 172.28.1.5

networks:
  shopnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
